// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAym89GfEgxahpd6wHDxaisKViPGf2ypAM',
    appId: '1:958331775033:web:eabdd07a9add72d6c985e8',
    messagingSenderId: '958331775033',
    projectId: 'pupiltube',
    authDomain: 'pupiltube.firebaseapp.com',
    storageBucket: 'pupiltube.appspot.com',
    measurementId: 'G-RQPXZJ3Y0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiVw1FjhgclazVvHz_H-lQz2eECBWIHWA',
    appId: '1:958331775033:android:445c37af33621439c985e8',
    messagingSenderId: '958331775033',
    projectId: 'pupiltube',
    storageBucket: 'pupiltube.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU4_KuIbGwXV44tRJS8lwqf-SVgCne47k',
    appId: '1:958331775033:ios:e015755b00bde403c985e8',
    messagingSenderId: '958331775033',
    projectId: 'pupiltube',
    storageBucket: 'pupiltube.appspot.com',
    iosBundleId: 'com.pupiltube.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU4_KuIbGwXV44tRJS8lwqf-SVgCne47k',
    appId: '1:958331775033:ios:e015755b00bde403c985e8',
    messagingSenderId: '958331775033',
    projectId: 'pupiltube',
    storageBucket: 'pupiltube.appspot.com',
    iosBundleId: 'com.pupiltube.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAym89GfEgxahpd6wHDxaisKViPGf2ypAM',
    appId: '1:958331775033:web:1ca536ea7420cc1fc985e8',
    messagingSenderId: '958331775033',
    projectId: 'pupiltube',
    authDomain: 'pupiltube.firebaseapp.com',
    storageBucket: 'pupiltube.appspot.com',
    measurementId: 'G-3X3X8R023X',
  );
}
